### ISSUE TITLE
Wrong warning on Attribute

### ISSUE THREAD

**Issue by dscopra** [BADF00D/SwitchToNUnit3#13] opened 2017-10-27 09:54 UTC
I got a message "Reference to TestCaseSoruce has to be static", that make no sense at the current location:

![image](https://user-images.githubusercontent.com/13195823/32098570-719b2e54-bb0d-11e7-972f-83a4a1282c93.png)

**Comment by dscopra** [comment] 2017-11-01 06:48
![xmlelement](https://user-images.githubusercontent.com/13195823/32263213-0a38ff6e-bed9-11e7-9cae-0d7703198019.png)

**Comment by BADF00D** [comment] 2017-11-09 19:55
The problem is, the algorithm does not check what type the argument is of.

**Comment by BADF00D** [comment] 2017-11-13 07:06
Fixed in release 0.3

**Closed as completed by BADF00D** 2017-11-13 07:06 UTC
